#!/usr/bin/env perl

use VideoRedactor;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "VideoRedactor",
   ReceiveHandler => \&Receive);
$UNIVERSAL::videoredactor = VideoRedactor->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::videoredactor->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::videoredactor->Execute();
